### ISSUE TITLE
Add configuration option for award numbers that don't match

### ISSUE THREAD

**Issue by karenhanson** [eclipse-pass/pass-nihms-loader#20]
We need an easy way to configure:
1) the mapping between award numbers in the CSV that are in PASS but are not matched due to different formatting etc.
2) award numbers that will never map correctly because the Grant does not exist in PASS  - typically these are grants from a PI's previous institution or very old award numbers, for example.

This could be 2 properties files that are loaded and used as an additional lookup file during processing. It should be possible to update these easily between data loads.

**Comment by karenhanson** [comment]
I'm just realizing there may be a solution to this that does not require any changes, but it needs to be tested. In the `./cache` folder, there should be a file that maps `Award number` to `Grant.id`. It may be possible to simply add new valid mappings to this file as they are discovered rather than implementing a special config file for these mappings.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
